In [1]:
!pip install tensorflow

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

c:\Users\deepa\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6249, 599, 6299, 6224],
 [6249, 599, 6299, 5296],
 [6249, 5276, 6299, 556],
 [2448, 7100, 9665, 824, 1989],
 [2448, 7100, 9665, 824, 4550],
 [3425, 6249, 6070, 6299, 2000],
 [9152, 2835, 3604, 824]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6249  599 6299 6224]
 [   0    0    0    0 6249  599 6299 5296]
 [   0    0    0    0 6249 5276 6299  556]
 [   0    0    0 2448 7100 9665  824 1989]
 [   0    0    0 2448 7100 9665  824 4550]
 [   0    0    0 3425 6249 6070 6299 2000]
 [   0    0    0    0 9152 2835 3604  824]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\deepa\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step


array([[[ 4.26545776e-02, -9.12592560e-03,  4.73345257e-02,
         -2.06625350e-02,  1.82567127e-02, -6.29132986e-03,
         -2.24433076e-02,  8.61977413e-03,  3.24398279e-03,
          4.94514443e-02],
        [ 4.26545776e-02, -9.12592560e-03,  4.73345257e-02,
         -2.06625350e-02,  1.82567127e-02, -6.29132986e-03,
         -2.24433076e-02,  8.61977413e-03,  3.24398279e-03,
          4.94514443e-02],
        [ 4.26545776e-02, -9.12592560e-03,  4.73345257e-02,
         -2.06625350e-02,  1.82567127e-02, -6.29132986e-03,
         -2.24433076e-02,  8.61977413e-03,  3.24398279e-03,
          4.94514443e-02],
        [ 4.26545776e-02, -9.12592560e-03,  4.73345257e-02,
         -2.06625350e-02,  1.82567127e-02, -6.29132986e-03,
         -2.24433076e-02,  8.61977413e-03,  3.24398279e-03,
          4.94514443e-02],
        [-1.25577562e-02,  3.85054201e-03,  4.49136607e-02,
         -3.29033621e-02, -1.35903582e-02, -4.60945629e-02,
         -3.23702693e-02,  1.36585124e-02,  3.926100

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 6249,  599, 6299, 6224], dtype=int32)

In [16]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[ 0.04265458, -0.00912593,  0.04733453, -0.02066253,
          0.01825671, -0.00629133, -0.02244331,  0.00861977,
          0.00324398,  0.04945144],
        [ 0.04265458, -0.00912593,  0.04733453, -0.02066253,
          0.01825671, -0.00629133, -0.02244331,  0.00861977,
          0.00324398,  0.04945144],
        [ 0.04265458, -0.00912593,  0.04733453, -0.02066253,
          0.01825671, -0.00629133, -0.02244331,  0.00861977,
          0.00324398,  0.04945144],
        [ 0.04265458, -0.00912593,  0.04733453, -0.02066253,
          0.01825671, -0.00629133, -0.02244331,  0.00861977,
          0.00324398,  0.04945144],
        [-0.01255776,  0.00385054,  0.04491366, -0.03290336,
         -0.01359036, -0.04609456, -0.03237027,  0.01365851,
          0.03926101, -0.03905996],
        [-0.00010369, -0.04212968,  0.04444332,  0.01002642,
          0.04381   ,  0.04617978,  0.03826758, -0.02647759,
         -0.02486614,  0.0417111 ],
        [-0.0387298 , -0.0215476 , -0.03931075,  0.0